# comandos shell para crear y configurar la bd
# crea bd, crea usuario y le da permisos
# version de kubectl
apiVersion: v1
# tipo de archivo
kind: ConfigMap
metadata:
  name: postgres-init-script-configmap
data:
  init.sh: |-
    #!/bin/bash
      set -e
      psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      CREATE USER billingapp WITH PASSWORD 'qwerty';
      CREATE DATABASE billingapp_db;
      GRANT ALL PRIVILEGES ON DATABASE billingapp_db TO billingapp;
      GRANT ALL ON SCHEMA public TO billingapp;
    EOSQL