# tipo de archivo, almacenamiento persistente independiente del ciclo de vida del pod
kind: PersistentVolume
# version del de API de kubectl
apiVersion: v1
metadata:
  name: postgres-volume
  labels:
    # plugin que es soportado por Amazon, Azure, etc..
    # local se refiere que el almacenamiento esta ubicado localmente en el equipo
    type: local
    app: postgres
spec:
  # disco creado manualmente de 5Gb
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    # muchos pods pueden leer y escribir
    - ReadWriteMany
  hostPath:
    # path donde se va a montar la BD persistente dentro del cluster de minikube
    path: "/mnt/data/"