# version de kubectl
apiVersion: v1
# tipo de archivo, secret indica que la info va cifrada
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
# indica que las variables en data sera un numero arbitrario de variables
type: Opaque
# datos de la BD con indo cifrada
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cXdlcnR5