# version de kubectl
apiVersion: v1
# tipo de archivo, secret indica que la info va cifrada
kind: Secret
metadata:
  name: pgadmin-secret
  labels:
    app: postgres
# indica que las variables en data sera un numero arbitrario de variables
type: Opaque
# datos de la BD con indo cifrada
data:
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AYWRtaW4uY29t
  PGADMIN_DEFAULT_PASSWORD: cXdlcnR5
  PGADMIN_PORT: ODA=