apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels:
    app: pgadmin
spec:
  selector:
  #type NodePort indica que usa el puerto del nodo pq es un solo nodo
   app: pgadmin
  type: NodePort
  ports:
  # puerto inteno y puerto expuesto
   - port: 80
     nodePort: 30200