#it is a reques of resource (persistence volume) from a pod by example, teh pod claim by a storage throug PVC
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi