kind: Service
apiVersion: v1
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:  
  ports:
  - name: postgres
    port: 5432
    nodePort : 30432 
  #type: LoadBalancer
  type: NodePort
  selector:
   app: postgres