kind: Service
apiVersion: v1
metadata:
  name: postgres-service
  labels:
    app: postgres
spec: 
  clusterIP: 10.96.1.2 
  ipFamilies:
  - IPv4
  ports:
  - name: postgres
    port: 5432
    nodePort : 30432 
  #type: LoadBalancer
  type: NodePort
  selector:
   app: postgres