/**
 * Digitalthinking Shool
 * Digitalthinking Shool API reference for developers, teh error handler is implement using   The IETF devised RFC 7807 effor, which creates a generalized error-handling schema. https://tools.ietf.org/html/rfc7807
 *
 * OpenAPI spec version: 1.0
 * Contact: https://digitalthinking.biz/es/ada-enterprise-core#contactus
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Person { 
    address?: string;
    documentNumber?: string;
    email?: string;
    id?: number;
    names?: string;
    phone?: string;
    surname?: string;
}
