apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-app-back-deployment
spec:
  selector:
   matchLabels:
    app: billing-app-back
  replicas: 3
  template:
    metadata:
      labels:
        app: billing-app-back
    spec:
      containers:
        - name: billing-app-back
          image: billingapp-back:0.0.4       
          ports:
            - containerPort: 7080
              name: billingappbport