apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-app-front-deployment
spec:
  selector:
   matchLabels:
    app: billing-app-front
  replicas: 2
  template:
    metadata:
      labels:
        app: billing-app-front
    spec:
      containers:
        - name: billing-app-front
          image: billingapp-front:0.0.4 
          ports:
            - containerPort: 80
              name: billingappfport